/**********************************************************************
 * Extern for deck
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var deck = {
  "ArcLayer": {
    "defaultProps": {
      "fp64": {},
      "getSourceColor": {},
      "getSourcePosition": function () {},
      "getStrokeWidth": {},
      "getTargetColor": {},
      "getTargetPosition": function () {}
    },
    "layerName": {}
  },
  "AttributeManager": function () {},
  "COORDINATE_SYSTEM": {
    "IDENTITY": {},
    "LNGLAT": {},
    "LNGLAT_EXPERIMENTAL": {},
    "LNGLAT_OFFSETS": {},
    "METERS": {},
    "METER_OFFSETS": {}
  },
  "CompositeLayer": {
    "defaultProps": {
      "animation": {},
      "autoHighlight": {},
      "coordinateOrigin": {},
      "coordinateSystem": {},
      "data": {
        "async": {},
        "type": {},
        "value": {}
      },
      "dataComparator": {},
      "dataTransform": function () {},
      "fetch": function () {},
      "framebuffer": {},
      "getPolygonOffset": function () {},
      "highlightColor": {},
      "highlightedObjectIndex": {},
      "numInstances": {},
      "onClick": function () {},
      "onHover": function () {},
      "opacity": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "parameters": {},
      "pickable": {},
      "uniforms": {},
      "updateTriggers": {},
      "visible": {}
    },
    "layerName": {}
  },
  "Controller": function () {},
  "Deck": {
    "defaultProps": {
      "controller": {},
      "debug": {},
      "drawPickingColors": {},
      "effects": {},
      "getCursor": function () {},
      "gl": {},
      "glOptions": {},
      "height": {},
      "id": {},
      "layerFilter": {},
      "layers": {},
      "onAfterRender": function () {},
      "onBeforeRender": function () {},
      "onLayerClick": {},
      "onLayerHover": {},
      "onLoad": function () {},
      "onResize": function () {},
      "onViewStateChange": function () {},
      "onWebGLInitialized": function () {},
      "pickingRadius": {},
      "useDevicePixels": {},
      "views": {},
      "width": {}
    },
    "getPropTypes": function () {}
  },
  "DeckGL": {
    "defaultProps": {
      "controller": {},
      "debug": {},
      "drawPickingColors": {},
      "effects": {},
      "getCursor": function () {},
      "gl": {},
      "glOptions": {},
      "height": {},
      "id": {},
      "layerFilter": {},
      "layers": {},
      "onAfterRender": function () {},
      "onBeforeRender": function () {},
      "onLayerClick": {},
      "onLayerHover": {},
      "onLoad": function () {},
      "onResize": function () {},
      "onViewStateChange": function () {},
      "onWebGLInitialized": function () {},
      "pickingRadius": {},
      "useDevicePixels": {},
      "views": {},
      "width": {}
    },
    "getPropTypes": function () {}
  },
  "FirstPersonView": {
    "displayName": {}
  },
  "FlyToInterpolator": function () {},
  "GeoJsonLayer": {
    "defaultProps": {
      "elevationScale": {},
      "extruded": {},
      "filled": {},
      "fp64": {},
      "getElevation": {},
      "getFillColor": {},
      "getLineColor": {},
      "getLineDashArray": {},
      "getLineWidth": {},
      "getRadius": {},
      "lightSettings": {},
      "lineDashJustified": {},
      "lineJointRounded": {},
      "lineMiterLimit": {},
      "lineWidthMaxPixels": {},
      "lineWidthMinPixels": {},
      "lineWidthScale": {},
      "pointRadiusMaxPixels": {},
      "pointRadiusMinPixels": {},
      "pointRadiusScale": {},
      "stroked": {},
      "subLayers": {
        "LineLayer": {
          "defaultProps": {
            "dashJustified": {},
            "fp64": {},
            "getColor": {},
            "getDashArray": {},
            "getPath": function () {},
            "getWidth": {},
            "miterLimit": {},
            "rounded": {},
            "widthMaxPixels": {},
            "widthMinPixels": {},
            "widthScale": {}
          },
          "layerName": {}
        },
        "PointLayer": {
          "defaultProps": {
            "fp64": {},
            "getColor": {},
            "getPosition": function () {},
            "getRadius": {},
            "outline": {},
            "radiusMaxPixels": {},
            "radiusMinPixels": {},
            "radiusScale": {},
            "strokeWidth": {}
          },
          "layerName": {}
        },
        "PolygonLayer": {
          "defaultProps": {
            "elevationScale": {},
            "extruded": {},
            "filled": {},
            "fp64": {},
            "getElevation": {},
            "getFillColor": {},
            "getLineColor": {},
            "getPolygon": function () {},
            "lightSettings": {},
            "wireframe": {}
          },
          "layerName": {}
        }
      },
      "wireframe": {}
    },
    "layerName": {}
  },
  "GridCellLayer": {
    "defaultProps": {
      "cellSize": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "coverage": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationScale": {
        "min": {},
        "type": {},
        "value": {}
      },
      "extruded": {},
      "fp64": {},
      "getColor": {},
      "getElevation": {},
      "getPosition": function () {},
      "lightSettings": {}
    },
    "layerName": {}
  },
  "GridLayer": {
    "defaultProps": {
      "cellSize": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "colorDomain": {},
      "colorRange": {},
      "coverage": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationDomain": {},
      "elevationLowerPercentile": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationRange": {},
      "elevationScale": {},
      "elevationUpperPercentile": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "extruded": {},
      "fp64": {},
      "getColorValue": function () {},
      "getElevationValue": function () {},
      "getPosition": function () {},
      "lightSettings": {},
      "lowerPercentile": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "onSetColorDomain": function () {},
      "onSetElevationDomain": function () {},
      "upperPercentile": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      }
    },
    "layerName": {}
  },
  "HexagonCellLayer": {
    "defaultProps": {
      "angle": {},
      "coverage": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationScale": {
        "min": {},
        "type": {},
        "value": {}
      },
      "extruded": {},
      "fp64": {},
      "getCentroid": function () {},
      "getColor": {},
      "getElevation": {},
      "hexagonVertices": {},
      "lightSettings": {},
      "radius": {}
    },
    "layerName": {}
  },
  "HexagonLayer": {
    "defaultProps": {
      "colorDomain": {},
      "colorRange": {},
      "coverage": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationDomain": {},
      "elevationLowerPercentile": {},
      "elevationRange": {},
      "elevationScale": {
        "min": {},
        "type": {},
        "value": {}
      },
      "elevationUpperPercentile": {},
      "extruded": {},
      "fp64": {},
      "getColorValue": function () {},
      "getElevationValue": function () {},
      "getPosition": function () {},
      "hexagonAggregator": function () {},
      "lightSettings": {},
      "lowerPercentile": {},
      "onSetColorDomain": function () {},
      "onSetElevationDomain": function () {},
      "radius": {},
      "upperPercentile": {}
    },
    "layerName": {}
  },
  "IconLayer": {
    "defaultProps": {
      "fp64": {},
      "getAngle": {},
      "getColor": {},
      "getIcon": function () {},
      "getPosition": function () {},
      "getSize": {},
      "iconAtlas": {},
      "iconMapping": {
        "async": {},
        "type": {},
        "value": {}
      },
      "sizeScale": {}
    },
    "layerName": {}
  },
  "Layer": {
    "defaultProps": {
      "animation": {},
      "autoHighlight": {},
      "coordinateOrigin": {},
      "coordinateSystem": {},
      "data": {
        "async": {},
        "type": {},
        "value": {}
      },
      "dataComparator": {},
      "dataTransform": function () {},
      "fetch": function () {},
      "framebuffer": {},
      "getPolygonOffset": function () {},
      "highlightColor": {},
      "highlightedObjectIndex": {},
      "numInstances": {},
      "onClick": function () {},
      "onHover": function () {},
      "opacity": {
        "max": {},
        "min": {},
        "type": {},
        "value": {}
      },
      "parameters": {},
      "pickable": {},
      "uniforms": {},
      "updateTriggers": {},
      "visible": {}
    },
    "layerName": {}
  },
  "LayerManager": function () {},
  "LineLayer": {
    "defaultProps": {
      "fp64": {},
      "getColor": {},
      "getSourcePosition": function () {},
      "getStrokeWidth": {},
      "getTargetPosition": function () {}
    },
    "layerName": {}
  },
  "LinearInterpolator": function () {},
  "MapController": function () {},
  "MapView": {
    "displayName": {}
  },
  "OrbitView": {
    "displayName": {}
  },
  "OrthographicView": {
    "displayName": {}
  },
  "PathLayer": {
    "defaultProps": {
      "dashJustified": {},
      "fp64": {},
      "getColor": {},
      "getDashArray": {},
      "getPath": function () {},
      "getWidth": {},
      "miterLimit": {},
      "rounded": {},
      "widthMaxPixels": {},
      "widthMinPixels": {},
      "widthScale": {}
    },
    "layerName": {}
  },
  "PerspectiveView": {
    "displayName": {}
  },
  "PointCloudLayer": {
    "defaultProps": {
      "fp64": {},
      "getColor": {},
      "getNormal": {},
      "getPosition": function () {},
      "lightSettings": {},
      "radiusPixels": {}
    },
    "layerName": {}
  },
  "PolygonLayer": {
    "defaultProps": {
      "elevationScale": {},
      "extruded": {},
      "filled": {},
      "fp64": {},
      "getElevation": {},
      "getFillColor": {},
      "getLineColor": {},
      "getLineDashArray": {},
      "getLineWidth": {},
      "getPolygon": function () {},
      "lightSettings": {},
      "lineDashJustified": {},
      "lineJointRounded": {},
      "lineMiterLimit": {},
      "lineWidthMaxPixels": {},
      "lineWidthMinPixels": {},
      "lineWidthScale": {},
      "stroked": {},
      "wireframe": {}
    },
    "layerName": {}
  },
  "ScatterplotLayer": {
    "defaultProps": {
      "fp64": {},
      "getColor": {},
      "getPosition": function () {},
      "getRadius": {},
      "outline": {},
      "radiusMaxPixels": {},
      "radiusMinPixels": {},
      "radiusScale": {},
      "strokeWidth": {}
    },
    "layerName": {}
  },
  "ScreenGridLayer": {
    "defaultProps": {
      "cellMarginPixels": {
        "max": {},
        "min": {},
        "value": {}
      },
      "cellSizePixels": {
        "min": {},
        "value": {}
      },
      "colorDomain": {},
      "colorRange": {},
      "getPosition": function () {},
      "getWeight": function () {},
      "gpuAggregation": {}
    },
    "layerName": {}
  },
  "TRANSITION_EVENTS": {
    "BREAK": {},
    "IGNORE": {},
    "SNAP_TO_END": {}
  },
  "TextLayer": {
    "defaultProps": {
      "characterSet": {},
      "fontFamily": {},
      "fp64": {},
      "getAlignmentBaseline": {},
      "getAngle": {},
      "getColor": {},
      "getPixelOffset": {},
      "getPosition": function () {},
      "getSize": {},
      "getText": function () {},
      "getTextAnchor": {},
      "sizeScale": {}
    },
    "layerName": {}
  },
  "ThirdPersonView": {
    "displayName": {}
  },
  "VERSION": {},
  "View": function () {},
  "Viewport": {
    "displayName": {}
  },
  "WebMercatorViewport": {
    "displayName": {}
  },
  "_Effect": function () {},
  "_EffectManager": function () {},
  "_FirstPersonController": function () {},
  "_GPUGridAggregator": function () {},
  "_MultiIconLayer": {
    "defaultProps": {
      "getAnchorX": function () {},
      "getAnchorY": function () {},
      "getLengthOfQueue": function () {},
      "getPixelOffset": {},
      "getShiftInQueue": function () {}
    },
    "layerName": {}
  },
  "_OrbitController": function () {},
  "_ReflectionEffect": function () {},
  "_SolidPolygonLayer": {
    "defaultProps": {
      "elevationScale": {},
      "extruded": {},
      "filled": {},
      "fp64": {},
      "getElevation": {},
      "getFillColor": {},
      "getLineColor": {},
      "getPolygon": function () {},
      "lightSettings": {},
      "wireframe": {}
    },
    "layerName": {}
  },
  "experimental": {
    "BinSorter": function () {},
    "defaultColorRange": {},
    "fillArray": function () {},
    "flattenVertices": function () {},
    "getLinearScale": function () {},
    "getQuantizeScale": function () {},
    "linearScale": function () {},
    "quantizeScale": function () {}
  },
  "lighting": {
    "dependencies": {},
    "deprecations": {},
    "getUniforms": function () {},
    "name": {},
    "vs": {}
  },
  "log": {
    "LOG_THROTTLE_TIMEOUT": {},
    "VERSION": {},
    "_decorateMessage": function () {},
    "_deltaTs": {},
    "_getElapsedTime": function () {},
    "_getLogFunction": function () {},
    "_logImageInBrowser": function () {},
    "_logImageInNode": function () {},
    "_normalizeArguments": function () {},
    "_normalizePriority": function () {},
    "_parseArguments": function () {},
    "_shouldLog": function () {},
    "_startTs": {},
    "_storage": {
      "config": {
        "enabled": {},
        "priority": {}
      },
      "id": {},
      "storage": {
        "__probe-deck__": {},
        "__probe-luma__": {},
        "clear": function () {},
        "getItem": function () {},
        "key": function () {},
        "length": {},
        "removeItem": function () {},
        "setItem": function () {}
      }
    },
    "deprecated": function () {},
    "enable": function () {},
    "error": function () {},
    "getDelta": function () {},
    "getLevel": function () {},
    "getPriority": function () {},
    "getTotal": function () {},
    "group": function () {},
    "groupCollapsed": function () {},
    "groupEnd": function () {},
    "id": {},
    "image": function () {},
    "info": function () {},
    "isEnabled": function () {},
    "log": function () {},
    "once": function () {},
    "probe": function () {},
    "removed": function () {},
    "setLevel": function () {},
    "table": function () {},
    "time": function () {},
    "timeEnd": function () {},
    "timeStamp": function () {},
    "trace": function () {},
    "userData": {},
    "warn": function () {},
    "withGroup": function () {}
  },
  "project": {
    "dependencies": {},
    "deprecations": {},
    "getUniforms": function () {},
    "name": {},
    "vs": {}
  },
  "project64": {
    "dependencies": {},
    "deprecations": {},
    "getUniforms": function () {},
    "name": {},
    "vs": {}
  },
  "version": {}
};
/**********************************************************************
 * End Generated Extern for deck
/**********************************************************************/
